services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taks_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
